$(document).ready(function(){
	$("#s1").mouseover(function(){
			$("#h1").removeClass("hid");
		});
	$("#s1").mouseout(function(){
			$("#h1").addClass("hid");
		});
	$("#s4").mouseover(function(){
			$("#h4").removeClass("hid");
		});
	$("#s4").mouseout(function(){
			$("#h4").addClass("hid");
		});
	});
