$(document).ready(function(){
	$(".r11").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt1").css("visibility","visible");
	});
	$(".r11").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt1").css("visibility","hidden");
	});
	$(".r12").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt2").css("visibility","visible");
	});
	$(".r12").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt2").css("visibility","hidden");
	});
	$(".r13").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt3").css("visibility","visible");
	});
	$(".r13").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt3").css("visibility","hidden");
	});
	$(".r14").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt4").css("visibility","visible");
	});
	$(".r14").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt4").css("visibility","hidden");
	});
	$(".r15").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt5").css("visibility","visible");
	});
	$(".r15").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt5").css("visibility","hidden");
	});
	$(".r16").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt6").css("visibility","visible");
	});
	$(".r16").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt6").css("visibility","hidden");
	});
	$(".r17").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt7").css("visibility","visible");
	});
	$(".r17").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt7").css("visibility","hidden");
	});
	$(".r18").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt8").css("visibility","visible");
	});
	$(".r18").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt8").css("visibility","hidden");
	});
	$(".r19").mouseover(function(){
		$(this).css("background-color","#D35400");
		$(".bt9").css("visibility","visible");
	});
	$(".r19").mouseout(function(){
		$(this).css("background-color","#E67E22");
		$(".bt9").css("visibility","hidden");
	});
});